name: "Post multiple coverage reports"
description: "Get Code Coverage"
branding:
  icon: "check"
  color: "blue"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: "src/react"
  reports-array:
    description: "All reports array"
    required: false
    default: "jest.common.json jest.web.json jest.pixel.json"
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  check-name:
    description: "Status check name"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
